# Generated by Django 5.1.7 on 2025-03-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="Unnamed User", max_length=100),
        ),
    ]
