# Generated by Django 5.1.7 on 2025-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuser_is_blocked_customuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
