# Generated by Django 5.1.7 on 2025-04-02 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_customuser_is_verified_customuser_otp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Busy", "Busy"),
                            ("Not Taking Work", "Not Taking Work"),
                        ],
                        default="Available",
                        max_length=15,
                    ),
                ),
                ("portfolio_links", models.JSONField(blank=True, default=list)),
                (
                    "verify_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_docs/"
                    ),
                ),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Verified", "Verified"),
                            ("Not Verified", "Not Verified"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("avg_rating", models.FloatField(default=0.0)),
            ],
        ),
    ]
