# Generated by Django 5.1.7 on 2025-04-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_job_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Applied", "Applied"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Applied",
                max_length=10,
            ),
        ),
    ]
