# Generated by Django 5.1.7 on 2025-04-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalprofile",
            name="denial_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
