# Generated by Django 5.1.7 on 2025-05-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_professionalprofile_denial_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
