# Generated by Django 5.1.7 on 2025-05-07 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_message_file_message_file_type_alter_message_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="professional_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
