# Generated by Django 5.1.7 on 2025-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_job_professional_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_absolute_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="conversation_files/%Y/%m/%d/"
            ),
        ),
    ]
