# Generated by Django 5.1.7 on 2025-05-30 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="admin_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="client_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="feedback_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="response_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("AWAITING_USER_RESPONSE", "Awaiting User Response"),
                    ("NEEDS_FURTHER_ACTION", "Needs Further Action"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
