# Generated by Django 5.1.7 on 2025-05-31 02:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_add_complaint_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="document",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload project documents, requirements, or reference files",
                max_length=255,
                null=True,
                verbose_name="document",
            ),
        ),
    ]
