# Generated by Django 5.1.7 on 2025-05-31 03:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_job_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalprofile",
            name="verify_doc",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload verification document (ID, degree, certificate, etc.)",
                max_length=255,
                null=True,
                verbose_name="verify_doc",
            ),
        ),
    ]
