# Generated by Django 5.1.7 on 2025-05-31 08:04

import account.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_alter_professionalprofile_verify_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=account.storage.LocalFileStorage(),
                upload_to="%Y/%m/%d/",
            ),
        ),
    ]
